trigger:
- main

variables:
  dockerHubServiceConnection: 'dockerhub'  # Debes configurar esto en Azure DevOps
  imageRepository: 'abeltran12/iac'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: '$(Build.BuildId)-$(Build.SourceBranchName)-$(Build.Repository.Name)-$(Date:yyyyMMdd.HHmm)'

  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build Docker Image
  jobs:
  - job: Build
    displayName: Build Docker Image
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build and tag Docker image
      inputs:
        command: build
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        tags: |
          latest
          $(tag)

    - task: Docker@2
      displayName: Push Docker image to Docker Hub
      inputs:
        command: push
        repository: $(imageRepository)
        tags: |
          latest
          $(tag)
        containerRegistry: $(dockerHubServiceConnection)
